// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrNEHuA2-FCt3tzL9UI6JKK3hGLqXqaJ4',
    appId: '1:607113121137:web:servicios-hogar-rd',
    messagingSenderId: '607113121137',
    projectId: 'servicios-hogar-rd',
    authDomain: 'servicios-hogar-rd.firebaseapp.com',
    storageBucket: 'servicios-hogar-rd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNEHuA2-FCt3tzL9UI6JKK3hGLqXqaJ4',
    appId: '1:607113121137:android:com.app.hogar',
    messagingSenderId: '607113121137',
    projectId: 'servicios-hogar-rd',
    storageBucket: 'servicios-hogar-rd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNEHuA2-FCt3tzL9UI6JKK3hGLqXqaJ4',
    appId: '1:607113121137:ios:com.app.hogar',
    messagingSenderId: '607113121137',
    projectId: 'servicios-hogar-rd',
    storageBucket: 'servicios-hogar-rd.firebasestorage.app',
    iosBundleId: 'com.app.hogar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNEHuA2-FCt3tzL9UI6JKK3hGLqXqaJ4',
    appId: '1:607113121137:ios:com.app.hogar',
    messagingSenderId: '607113121137',
    projectId: 'servicios-hogar-rd',
    storageBucket: 'servicios-hogar-rd.firebasestorage.app',
    iosBundleId: 'com.app.hogar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrNEHuA2-FCt3tzL9UI6JKK3hGLqXqaJ4',
    appId: '1:607113121137:web:servicios-hogar-rd',
    messagingSenderId: '607113121137',
    projectId: 'servicios-hogar-rd',
    authDomain: 'servicios-hogar-rd.firebaseapp.com',
    storageBucket: 'servicios-hogar-rd.firebasestorage.app',
  );
}
