// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps in DEVELOPMENT.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TU_API_KEY_DEV_WEB_AQUI', // Reemplaza con la clave real
    appId: '1:TU_PROJECT_NUMBER:web:servicios-hogar-rd-dev',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'servicios-hogar-rd-dev',
    authDomain: 'servicios-hogar-rd-dev.firebaseapp.com',
    storageBucket: 'servicios-hogar-rd-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TU_API_KEY_DEV_ANDROID_AQUI', // Reemplaza con la clave real
    appId: '1:TU_PROJECT_NUMBER:android:com.app.hogar.dev',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'servicios-hogar-rd-dev',
    storageBucket: 'servicios-hogar-rd-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TU_API_KEY_DEV_IOS_AQUI', // Reemplaza con la clave real
    appId: '1:TU_PROJECT_NUMBER:ios:com.app.hogar.dev',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'servicios-hogar-rd-dev',
    storageBucket: 'servicios-hogar-rd-dev.firebasestorage.app',
    iosBundleId: 'com.app.hogar.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_API_KEY_DEV_IOS_AQUI', // Reemplaza con la clave real
    appId: '1:TU_PROJECT_NUMBER:ios:com.app.hogar.dev',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'servicios-hogar-rd-dev',
    storageBucket: 'servicios-hogar-rd-dev.firebasestorage.app',
    iosBundleId: 'com.app.hogar.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TU_API_KEY_DEV_WEB_AQUI', // Reemplaza con la clave real
    appId: '1:TU_PROJECT_NUMBER:web:servicios-hogar-rd-dev',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'servicios-hogar-rd-dev',
    authDomain: 'servicios-hogar-rd-dev.firebaseapp.com',
    storageBucket: 'servicios-hogar-rd-dev.firebasestorage.app',
  );
}
