name: Flutter Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        cache: true
        
    - name: 📦 Get Dependencies
      run: flutter pub get
      
    - name: 🔍 Analyze Code
      run: flutter analyze
      
    - name: 🧪 Run Tests
      run: flutter test
      
    - name: 🏗️ Build Debug APK
      run: flutter build apk --debug
      
    - name: 🏗️ Build Release APK (Main Branch Only)
      if: github.ref == 'refs/heads/main'
      run: flutter build apk --release
      
    - name: 📱 Upload APK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk-${{ github.ref_name }}
        path: build/app/outputs/flutter-apk/
        retention-days: 30
        
    - name: 📊 Build Summary
      run: |
        echo "## 🎉 Build Completed Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Flutter Version:** 3.35.3" >> $GITHUB_STEP_SUMMARY
        echo "- **APK Files:** Available in Artifacts" >> $GITHUB_STEP_SUMMARY
