name: Flutter Web Diagnostic

on:
  workflow_dispatch:

jobs:
  web-diagnostic:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      
    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        cache: true
        
    - name: 📊 System Info
      run: |
        echo "## 🔍 Web Build System Info" >> $GITHUB_STEP_SUMMARY
        echo "- **OS:** $(uname -a)" >> $GITHUB_STEP_SUMMARY
        echo "- **Flutter:** $(flutter --version | head -1)" >> $GITHUB_STEP_SUMMARY
        echo "- **Dart:** $(dart --version | head -1)" >> $GITHUB_STEP_SUMMARY
        
    - name: 📦 Get Dependencies
      run: flutter pub get
      
    - name: 🔍 Analyze Code
      run: flutter analyze --no-fatal-infos
      continue-on-error: true
      
    - name: 🏗️ Build Web (Verbose)
      run: |
        echo "=== Starting Web Build ==="
        flutter build web --verbose
      continue-on-error: true
      
    - name: 📱 Upload Web Build (If Available)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: web-diagnostic
        path: build/web/
        retention-days: 30
        
    - name: 📊 Diagnostic Summary
      run: |
        echo "## 🔍 Web Diagnostic Complete" >> $GITHUB_STEP_SUMMARY
        echo "- **Status:** Check logs above for details" >> $GITHUB_STEP_SUMMARY
        echo "- **Web Build:** Available in Artifacts (if build succeeded)" >> $GITHUB_STEP_SUMMARY
